# Generated by Django 6.0.3 on 2026-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_phone_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор сайта'),
        ),
    ]
