# Generated by Django 6.0.3 on 2026-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tilda_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='Путь к контенту (авто)'),
        ),
        migrations.AddField(
            model_name='course',
            name='tilda_zip',
            field=models.FileField(blank=True, null=True, upload_to='course_zips/', verbose_name='ZIP с Тильды'),
        ),
    ]
