# Generated by Django 6.0.3 on 2026-03-31 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tilda_path_course_tilda_zip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tilda_path',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tilda_zip',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('paid_1', 'Курс 1'), ('paid_2', 'Курс 2'), ('paid_3', 'Курс 3'), ('paid_4', 'Курс 4')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Занято')),
            ],
            options={
                'verbose_name': 'Доступный слот',
                'verbose_name_plural': 'Доступные слоты',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tilda_url', models.URLField(verbose_name='Ссылка на страницу Tilda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.lesson')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='courses.availableslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
    ]
