# Generated by Django 6.0.3 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_tilda_path_remove_course_tilda_zip_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE courses_lesson
                DROP COLUMN IF EXISTS tilda_url;

                ALTER TABLE courses_lesson
                ADD COLUMN IF NOT EXISTS tilda_path varchar(500);

                ALTER TABLE courses_lesson
                ADD COLUMN IF NOT EXISTS zip_file varchar(255);
            """,
            reverse_sql=""
        )
    ]
