# Generated by Django 6.0.3 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_tilda_path_remove_course_tilda_zip_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE courses_lesson DROP COLUMN IF EXISTS tilda_url;",
            reverse_sql="ALTER TABLE courses_lesson ADD COLUMN tilda_url varchar(200);"
        ),
        migrations.AddField(
            model_name='lesson',
            name='tilda_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Путь к странице Tilda'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_zip/', verbose_name='ZIP архив'),
        ),
    ]
