# Generated by Django 6.0.3 on 2026-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_tilda_url_lesson_tilda_path_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE courses_meeting
                ADD COLUMN IF NOT EXISTS meet_link varchar(255);
            """,
            reverse_sql="""
                ALTER TABLE courses_meeting
                DROP COLUMN IF EXISTS meet_link;
            """
        )
    ]
