# Generated by Django 6.0.3 on 2026-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_tilda_url_lesson_tilda_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на встречу (Google Meet)'),
        ),
    ]
