# Generated by Django 6.0.3 on 2026-04-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_meeting_meet_link'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    CREATE TABLE IF NOT EXISTS courses_lessonvideo (
                        id BIGSERIAL PRIMARY KEY,
                        title VARCHAR(200) NOT NULL,
                        video_file VARCHAR(100) NOT NULL,
                        "order" INTEGER NOT NULL DEFAULT 0,
                        lesson_id BIGINT NOT NULL REFERENCES courses_lesson(id) ON DELETE CASCADE
                    );
                    """,
            reverse_sql="DROP TABLE IF EXISTS courses_lessonvideo;"
        )
    ]
