# Generated by Django 6.0.3 on 2026-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание видео'),
        ),
    ]
