# Generated by Django 6.0.3 on 2026-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonvideo'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    ALTER TABLE courses_lessonvideo
                    ADD COLUMN IF NOT EXISTS description TEXT;
                    """,
            reverse_sql="""
                    ALTER TABLE courses_lessonvideo
                    DROP COLUMN IF EXISTS description;
                    """
        )
    ]
