# Generated by Django 6.0.3 on 2026-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonvideo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачена'), ('paid', 'Оплачена')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('free', 'Gratis'), ('paid_1', 'Curso 1'), ('paid_2', 'Curso 2'), ('paid_3', 'Curso 3'), ('paid_4', 'Curso 4')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
