# Generated by Django 6.0.3 on 2026-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_meeting_payment_status_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'No se paga'), ('paid', 'Pagado')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
